FROM golang:1.20.2-alpine AS build
RUN apk add build-base
RUN apk add xz-dev
RUN apk add linux-headers

WORKDIR /go/src/github.com/onepeerlabs/w3kipedia

COPY go.mod go.sum /go/src/github.com/onepeerlabs/w3kipedia
RUN go mod download

COPY . /go/src/github.com/onepeerlabs/w3kipedia

RUN cd cmd/uploader && go build -o uploader && mv uploader ../../uploader
ENTRYPOINT ["./uploader"]
