/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fave_api

type Collection struct {
	// Name of the collection
	Name string `json:"name,omitempty"`
	// The indexes of the collection for fairOS-dfs document store.
	Indexes []Index `json:"indexes,omitempty"`
}
