/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fave_api

// This is an object for specifying which fields to index in fairOS document store while Collection creation
type Index struct {
	// The filed name to index
	FieldName string `json:"fieldName,omitempty"`
	// Type of the field to index. Types can be \"string\", \"number\", \"map\", \"list\"
	FieldType string `json:"fieldType,omitempty"`
}
