/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package fave_api

// An ok response given by FaVe end-points.
type OkResponse struct {
	Message string `json:"message,omitempty"`
}
