/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Add the documents to the collection.
type AddDocumentsRequest struct {
	// The actual list of Objects.
	Documents []Document `json:"documents,omitempty"`
	// Name of the collection as URI relative to the schema URL.
	Name string `json:"name,omitempty"`
	// Array of properties to be indexed.
	PropertiesToIndex []string `json:"propertiesToIndex,omitempty"`
}
