/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Get the nearest documents from the collection.
type NearestDocumentsRequest struct {
	// The text to search for.
	Text string `json:"text,omitempty"`
	// Name of the collection as URI relative to the schema URL.
	Name     string  `json:"name,omitempty"`
	Distance float32 `json:"distance,omitempty"`
}
