/*
 * fave
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0-prealpha
 * Contact: sabyasachi@datafund.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Collection struct {
	// Name of the collection as URI relative to the schema URL.
	Name string `json:"name,omitempty"`
	// The indexes of the collection.
	Indexes interface{} `json:"indexes,omitempty"`
}
